# Generated by Django 2.2 on 2019-04-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agroglifos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.CharField(default='N/D', max_length=2000)),
                ('uuid', models.CharField(default='-- -- --', max_length=300)),
                ('url', models.URLField(default='-- -- --', max_length=300)),
            ],
        ),
    ]
