# Generated by Django 2.2 on 2019-04-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroglifos', '0002_agroglifos_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='agroglifos',
            name='url',
            field=models.URLField(default='-- -- --'),
        ),
    ]
