# Generated by Django 2.2 on 2019-04-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agroglifos', '0005_auto_20190421_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='agroglifos',
            name='uuid',
            field=models.CharField(default='-- -- --', max_length=300),
        ),
    ]
